# Generated by Django 4.0.3 on 2022-07-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phrases', to='phrasebook.chapter', verbose_name='chapter'),
        ),
    ]
