# Generated by Django 4.0.3 on 2022-07-16 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phrasebook', '0003_phrase_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraseaudio',
            name='user_contributed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user contributed'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='transcription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transcription'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='translation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='translation'),
        ),
    ]
